import { FontAwesome5 } from "@expo/vector-icons";
import { FontAwesome6 } from "@expo/vector-icons";

export const DARK_BG_COLOR_VALUE = "34, 38, 39";
export const DARK_CARD_BG_COLOR_VALUE = "44, 44, 46";
export const DARK_INPUT_BG_COLOR_VALUE = "53, 57, 60";
export const HIGHLIGHTER_BLUE_COLOR_VALUE = "11, 132, 255";
export const DARK_INPUT_ICON_COLOR_VALUE = "162, 164, 171";

export const IOS_LIGHT_BLUE = "#5fc9f8";
export const IOS_YELLOW = "#fecb2e";
export const IOS_ORANGE = "#fd9426";
export const IOS_RED = "#fc3158";
export const IOS_GREEN = "#53d769";
export const IOS_BLUE = "#147efb";
export const IOS_LIGHT_GRAY = "#8e8e93";
export const IOS_GRAY = "#474747";
export const IOS_PURPLE = "#bf5af2";
export const IOS_TEXT_GRAY = "#8e8e93";
export const IOS_PRESSED_GRAY = "#222222";
export const IOS_ICON_GRAY = "#9b9f9f";
export const IOS_BUTTON_GRAY = "#1f282a";

export const FILTERS = {
  places: [
    { label: "All People & Places", value: null },
    { label: "Places", value: "2" },
    { label: "People", value: "1" },
  ],
  types: [
    { label: "All Types", value: null },
    { label: "Hospital Based", value: true },
    { label: "Non Hospital Based", value: false },
  ],
  genders: [
    { label: "All Genders", value: null },
    { label: "Male", value: 1 },
    { label: "Female", value: 2 },
  ],
  acceptingStatus: [
    { label: "All Availability", value: null },
    { label: "Accepting New Patients", value: true },
    { label: "Not Accepting New Patients", value: false },
  ],
  radius: [
    { label: "30 miles", value: 30 },
    { label: "50 miles", value: 50 },
    { label: "100 miles", value: 100 },
  ],
  sortBy: [
    { label: "Price", value: "Price" },
    { label: "Distance", value: "Distance" },
    { label: "A-Z", value: "A-Z" },
    { label: "Z-A", value: "Z-A" },
  ],
  plans: [
    { label: "Evry Premier (EPO)", value: 1 },
    { label: "Evry Premier Plus (PPO)", value: 2 },
  ],
};

export type TFilterValue = { label: string; value: number };

export const STANDARD_PADDING = 14;
export const VERTICAL_PADDING = 12;

export const TRANSITION_DURATION = 600;

export const SPECIALTIES = [
  "AMBULATORY SURGERY CENTER",
  "BEHAVIORAL HEALTH",
  "COUNSELOR",
  "CHEMICAL DEPENDENCY",
  "BEHAVIORAL HEALTH FACILITIES",
  "EMERGENCY ROOM",
  "HOSPITAL",
  "ACUTE INPATIENT HOSPITAL",
  "IMAGING CENTER",
  "INFUSION CENTER",
  "INFUSION THERAPY FACILITY - CHEMOTHERAPY",
  "INFUSION THERAPY FACILITY",
  "INFUSION THERAPY",
  "LAB",
  "LABORATORY",
  "PRIMARY CARE",
  "URGENT CARE",
  "ACUPUNCTURE",
  "ADDICTION PSYCHIATRY",
  "ADOLESCENT AND CHILDREN MENTAL HEALTH",
  "ADULT DAY HEALTH",
  "ADVANCED HEART FAILURE",
  "AEROSPACE MEDICINE",
  "AIR TRANSPORTATION",
  "ALLERGY & IMMUNOLOGY",
  "ANATOMIC PATHOLOGY",
  "ANESTHESIOLOGIST ASSISTANT",
  "ANESTHESIOLOGY",
  "AUDIOLOGY",
  "BARIATRIC SURGERY",
  "BEHAVIOR ANALYST",
  "BEHAVIOR ANALYST (AUTISM)",
  "BREAST SURGERY",
  "CARDIAC ELECTROPHYSIOLOGY",
  "CARDIAC SURGERY PROGRAM",
  "CARDIOLOGY",
  "CARDIOLOGY - ADULT",
  "CARDIOLOGY - ELECTROPHYSIOLOGY",
  "CARDIOVASCULAR DISEASE",
  "CARDIOVASCULAR MEDICINE",
  "CERTIFIED NURSE ANESTHETIST",
  "CHILDRENS HOSPITAL",
  "CHIROPRACTOR",
  "CHIROPRACTOR - REHABILITATION",
  "CLINIC",
  "CLINIC/CENTER",
  "CLINICAL PATHOLOGY",
  "CLINICAL SOCIAL WORKER",
  "COLON & RECTAL SURGERY",
  "COMMUNITY/RETAIL PHARMACY",
  "CRITICAL CARE MEDICINE",
  "DENTIST",
  "DERMATOLOGY",
  "DERMATOPATHOLOGY",
  "DIABETES",
  "DIABETES & METABOLISM",
  "DIAGNOSTIC RADIOLOGY",
  "DIALYSIS",
  "DIETITIAN",
  "DURABLE MEDICAL EQUIPMENT",
  "ELETROPHYSIOLOGY",
  "EMERGENCY MEDICAL SERVICES",
  "EMERGENCY MEDICINE",
  "ENDOCRINOLOGY",
  "EYEWEAR SUPPLIER (EQUIPMENT, NOT THE SERVICE)",
  "FACIAL PLASTIC RECONSTRUCTIVE SURGERY",
  "FACIAL PLASTIC SURGERY",
  "FAMILY & MARRIAGE COUNSELING",
  "FAMILY MEDICINE",
  "FEMALE PELVIC MEDICINE, PLASTIC & RECONSTRUCTIVE SURGERY",
  "FERTILITY",
  "FOOT & ANKLE SURGERY",
  "FORENSIC PSYCHIATRY",
  "GASTROENTEROLOGY",
  "GENERAL PRACTICE",
  "GENERAL SURGERY",
  "GENERAL SURGERY - VASCULAR",
  "GENETIC COUNSELOR",
  "GERIATRIC MEDICINE",
  "GROUND TRANSPORTATION",
  "GYNECOLOGIC ONCOLOGY",
  "GYNECOLOGY",
  "HEAD & NECK SURGERY",
  "HEAD AND NECK SURGERY",
  "HEART TRANSPLANT PROGRAM",
  "HEMATOLOGY",
  "HEMATOLOGY & ONCOLOGY",
  "HEPATOBILIARY SURGERY",
  "HOME HEALTH",
  "HOME HEALTH / INFUSION THERAPY",
  "HOME INFUSION THERAPY",
  "HOME NURSING SERVICES",
  "HOME PHYSICAL THERAPY SERVICE",
  "HOSPICE",
  "HOSPICE AND PALLIATIVE CARE",
  "HOSPITALIST",
  "HYPERBARIC MEDICINE",
  "HYPERBARIC MEDICINE - WOUND CARE",
  "INFECTIOUS DISEASE",
  "INTERNAL MEDICINE",
  "INTERVENTIONAL CARDIOLOGY",
  "INTERVENTIONAL PAIN MANAGEMENT",
  "LACTATION CONSULTANT",
  "LICENSED CLINICAL SOCIAL WORKER",
  "LICENSED PROFESSIONAL COUNSELOR",
  "LITHOTRIPSY",
  "MAMMOGRAPHY",
  "MATERNAL & FETAL MEDICINE",
  "MEDICAL EQUIPMENT",
  "MEDICAL SUPPLIES",
  "MENTAL HEALTH",
  "MENTAL HEALTH FACILITY",
  "MIDWIFE",
  "MOHS-MICROGRAPHIC SURGERY",
  "NEONATALOGY",
  "NEONATOLOGY",
  "NEPHROLOGY",
  "NEURO-ONCOLOGY",
  "NEUROCRITICAL CARE",
  "NEUROLOGICAL SURGERY",
  "NEUROLOGY",
  "NEUROLOGY - EPILEPSY",
  "NEUROMUSCULOSKELETAL MEDICINE",
  "NEUROPHYSIOLOGY",
  "NEURORADIOLOGY",
  "NEUROSURGERY",
  "NUCLEAR MEDICINE",
  "NURSE ANESTHETIST",
  "NURSE PRACTITIONER",
  "NURSE PRACTITIONER - ACUTE CARE",
  "NURSE PRACTITIONER - ADULT",
  "NURSE PRACTITIONER - EMERGENCY MEDICINE",
  "NURSE PRACTITIONER - FAMILY",
  "NURSE PRACTITIONER - GERIATRIC",
  "NURSE PRACTITIONER - GERONTOLOGY",
  "NURSE PRACTITIONER - MENTAL HEALTH",
  "NURSE PRACTITIONER - NEONATALOGY",
  "NURSE PRACTITIONER - NEONATOLOGY",
  "NURSE PRACTITIONER - ORTHOPAEDIC SURGERY",
  "NURSE PRACTITIONER - PEDIATRIC",
  "NURSE PRACTITIONER - PRIMARY CARE",
  "NURSE PRACTITIONER - PSYCHIATRIC",
  "NURSE PRACTITIONER - PSYCHIATRY",
  "NURSE PRACTITIONER - WOMENS HEALTH",
  "NURSE SPECIALIST",
  "OBSTETRICS",
  "OBSTETRICS & GYNECOLOGY",
  "OCCUPATIONAL HEALTH",
  "OCCUPATIONAL MEDICINE",
  "OCCUPATIONAL THERAPY",
  "ONCOLOGY",
  "ONCOLOGY CERTIFIED NURSE",
  "OPHTHALMOLOGIC SURGERY",
  "OPHTHALMOLOGY",
  "OPHTHALMOLOGY - PLASTIC & RECONSTRUCTIVE SURGERY",
  "OPTOMETRY",
  "ORAL & MAXILLOFACIAL SURGERY",
  "ORTHOPEDIC SURGERY",
  "ORTHOPEDIC SURGERY - FOOT & ANKLE",
  "ORTHOPEDIC SURGERY - HAND SURGERY",
  "ORTHOPEDIC SURGERY - RECONSTRUCTIVE",
  "ORTHOPEDIC SURGERY - SPINE",
  "ORTHOPEDIC TRAUMA",
  "ORTHOPEDICS",
  "ORTHOTICS",
  "OSTEOPATHIC MANIPULATIVE MEDICINE",
  "OTHER",
  "OTOLARYNGOLOGY",
  "OUTPATIENT MENTAL HEALTH",
  "PAIN MANAGEMENT",
  "PALLIATIVE CARE",
  "PATHOLOGY",
  "PEDIATRIC",
  "PEDIATRIC ALLERGY & IMMUNOLOGY",
  "PEDIATRIC ANESTHESIOLOGY",
  "PEDIATRIC BEHAVIORAL & DEVELOPMENTAL",
  "PEDIATRIC CARDIOLOGY",
  "PEDIATRIC CHILD ABUSE",
  "PEDIATRIC CRITICAL CARE MEDICINE",
  "PEDIATRIC DENTISTRY",
  "PEDIATRIC DERMATOLOGY",
  "PEDIATRIC EMERGENCY MEDICINE",
  "PEDIATRIC ENDOCRINOLOGY",
  "PEDIATRIC GASTROENTEROLOGY",
  "PEDIATRIC HEMATOLOGY & ONCOLOGY",
  "PEDIATRIC HOSPITAL MEDICINE",
  "PEDIATRIC INFECTIOUS DISEASE",
  "PEDIATRIC NEONATAL-PERINATAL MEDICINE",
  "PEDIATRIC NEPHROLOGY",
  "PEDIATRIC NEUROLOGY",
  "PEDIATRIC NURSE PRACTITIONER",
  "PEDIATRIC ORTHOPEDIC SURGERY",
  "PEDIATRIC ORTHOPEDICS",
  "PEDIATRIC OTOLARYNGOLOGY",
  "PEDIATRIC PRIMARY CARE NURSE PRACTITIONER",
  "PEDIATRIC PSYCHIATRY",
  "PEDIATRIC PULMONOLOGY",
  "PEDIATRIC RADIOLOGY",
  "PEDIATRIC REHABILITATION MEDICINE",
  "PEDIATRIC RHEUMATOLOGY",
  "PEDIATRIC SLEEP MEDICINE",
  "PEDIATRIC SPORTS MEDICINE",
  "PEDIATRIC SURGERY",
  "PEDIATRIC UROLOGY",
  "PHARMACY",
  "PHYSICAL MEDICINE & REHABILITATION",
  "PHYSICAL MEDICINE & REHABILITATION - SPINE",
  "PHYSICAL THERAPY",
  "PHYSICIAN ASSISTANT",
  "PHYSICIAN ASSISTANT - FAMILY",
  "PHYSICIAN ASSISTANT - ORTHOPAEDIC SURGERY",
  "PLASTIC SURGERY",
  "PODIATRY",
  "PRENATAL CARE",
  "PROFESSIONAL COUNSELOR",
  "PROSTHESIS",
  "PROSTHETIC",
  "PSYCHIATRIC HOSPITAL",
  "PSYCHIATRY",
  "PSYCHIATRY - GERIATRIC",
  "PSYCHIATRY - SUBSTANCE ABUSE",
  "PSYCHOLOGY",
  "PUBLIC HEALTH & GENERAL PREVENTIVE MEDICINE",
  "PULMONARY DISEASE",
  "PULMONOLOGY",
  "RADIATION ONCOLOGY",
  "RADIOLOGY",
  "RADIOLOGY - ABDOMINAL RADIOLOGY",
  "RADIOLOGY - DIAGNOSTIC RADIOLOGY",
  "RADIOLOGY - VASCULAR & INTERVENTIONAL",
  "RECONSTRUCTIVE REARFOOT & ANKLE SURGERY",
  "REGISTERED NURSE",
  "REHABILITATION",
  "REHABILITATION FACILITY - SUBSTANCE ABUSE",
  "REHABILITATION HOSPITAL",
  "REHABILITATION PSYCHOLOGY",
  "REHABILITATION UNIT",
  "REPRODUCTIVE ENDOCRINOLOGY",
  "RESPIRATORY",
  "RESPIRATORY CARE SERVICES",
  "RETAIL CLINIC",
  "RETINA SPECIALIST",
  "RHEUMATOLOGY",
  "SKILLED NURSING FACILITY",
  "SKIN CANCER",
  "SLEEP MEDICINE",
  "SOCIAL WORKER",
  "SPECIALIST",
  "SPECIALTY HOSPITAL",
  "SPEECH & HEARING",
  "SPEECH THERAPY",
  "SPEECH-LANGUAGE PATHOLOGY",
  "SPORTS MEDICINE",
  "STUDENT IN AN ORGANIZED HEALTH CARE EDUCATION/TRAINING PROGRAM",
  "SUB-ACUTE",
  "SUBSTANCE ABUSE FACILITY",
  "SURGICAL ASSISTANT",
  "SURGICAL CRITICAL CARE",
  "SURGICAL ONCOLOGY",
  "SURGICAL PHYSICIAN ASSISTANT",
  "SURGICAL TECHNOLOGIST",
  "SURGICAL UROLOGY",
  "THORACIC & CARDIAC SURGERY",
  "THORACIC AND CARDIAC SURGERY",
  "THORACIC SURGERY",
  "TRANSPLANT CARDIOLOGY",
  "TRANSPLANT HEPATOLOGY",
  "TRANSPLANT PROGRAM - LIVER",
  "TRANSPLANT PROGRAM - PANCREAS",
  "TRANSPLANT SURGERY",
  "TRAUMA SURGERY",
  "UNDERSEA & HYPERBARIC MEDICINE",
  "UROLOGY",
  "VASCULAR NEUROLOGY",
  "VASCULAR SURGERY",
  "VISITING NURSE",
];

export type ProviderCardProps = {
  title: string;
  group: string;
  address: string;
  type: "hospital" | "individual";
  distance: string;
  phone: string;
  acceptNewPatients: boolean;
  specialties: string[];
  locationID?: string;
};

export const PROVIDER_DATA: ProviderCardProps[] = [
  {
    title: "METHODIST HOSPITAL FOR CONTINUING CARE",
    group: "Acute inpatient hospital",
    acceptNewPatients: true,
    address: "401 W CAMPBELL RD, RICHARDSON, TX, 75080",
    type: "hospital",
    distance: "1.22",
    phone: "4692041000",
    specialties: ["Acute inpatient hospital"],
    locationID: "1",
  },
  {
    title: "METHODIST HOSPITAL FOR CONTINUING CARE",
    group: "Acute inpatient hospital",
    acceptNewPatients: true,
    address: "401 W CAMPBELL RD, RICHARDSON, TX, 75080",
    type: "hospital",
    distance: "1.22",
    phone: "4692041000",
    specialties: ["Acute inpatient hospital"],
    locationID: "2",
  },
  {
    title: "METHODIST HOSPITAL FOR CONTINUING CARE",
    group: "Acute inpatient hospital",
    acceptNewPatients: true,
    address: "401 W CAMPBELL RD, RICHARDSON, TX, 75080",
    type: "hospital",
    distance: "1.22",
    phone: "4692041000",
    specialties: ["Acute inpatient hospital"],
    locationID: "3",
  },
  {
    title: "METHODIST HOSPITAL FOR CONTINUING CARE",
    group: "Acute inpatient hospital",
    acceptNewPatients: true,
    address: "401 W CAMPBELL RD, RICHARDSON, TX, 75080",
    type: "hospital",
    distance: "1.22",
    phone: "4692041000",
    specialties: ["Acute inpatient hospital"],
    locationID: "4",
  },
  {
    title: "METHODIST HOSPITAL FOR CONTINUING CARE",
    group: "Acute inpatient hospital",
    acceptNewPatients: true,
    address: "401 W CAMPBELL RD, RICHARDSON, TX, 75080",
    type: "hospital",
    distance: "1.22",
    phone: "4692041000",
    specialties: ["Acute inpatient hospital"],
    locationID: "5",
  },
  {
    title: "METHODIST HOSPITAL FOR CONTINUING CARE",
    group: "Acute inpatient hospital",
    acceptNewPatients: true,
    address: "401 W CAMPBELL RD, RICHARDSON, TX, 75080",
    type: "hospital",
    distance: "1.22",
    phone: "4692041000",
    specialties: ["Acute inpatient hospital"],
    locationID: "6",
  },
  {
    title: "METHODIST HOSPITAL FOR CONTINUING CARE",
    group: "Acute inpatient hospital",
    acceptNewPatients: true,
    address: "401 W CAMPBELL RD, RICHARDSON, TX, 75080",
    type: "hospital",
    distance: "1.22",
    phone: "4692041000",
    specialties: ["Acute inpatient hospital"],
    locationID: "7",
  },
  {
    title: "METHODIST HOSPITAL FOR CONTINUING CARE",
    group: "Acute inpatient hospital",
    acceptNewPatients: true,
    address: "401 W CAMPBELL RD, RICHARDSON, TX, 75080",
    type: "hospital",
    distance: "1.22",
    phone: "4692041000",
    specialties: ["Acute inpatient hospital"],
    locationID: "8",
  },
  {
    title: "METHODIST HOSPITAL FOR CONTINUING CARE",
    group: "Acute inpatient hospital",
    acceptNewPatients: true,
    address: "401 W CAMPBELL RD, RICHARDSON, TX, 75080",
    type: "hospital",
    distance: "1.22",
    phone: "4692041000",
    specialties: ["Acute inpatient hospital"],
    locationID: "9",
  },
  {
    title: "METHODIST HOSPITAL FOR CONTINUING CARE",
    group: "Acute inpatient hospital",
    acceptNewPatients: true,
    address: "401 W CAMPBELL RD, RICHARDSON, TX, 75080",
    type: "hospital",
    distance: "1.22",
    phone: "4692041000",
    specialties: ["Acute inpatient hospital"],
    locationID: "10",
  },
  {
    title: "METHODIST HOSPITAL FOR CONTINUING CARE",
    group: "Acute inpatient hospital",
    acceptNewPatients: true,
    address: "401 W CAMPBELL RD, RICHARDSON, TX, 75080",
    type: "hospital",
    distance: "1.22",
    phone: "4692041000",
    specialties: ["Acute inpatient hospital"],
    locationID: "11",
  },
];

export const RECENTS = [
  {
    title: "BAYLOR UNIVERSITY MEDICAL CENTER",
    distance: "1.2 mi",
    color: IOS_BLUE,
    icon: (size: number) => (
      <FontAwesome5 name="hospital" size={size || 24} color="white" />
    ),
  },
  {
    title: "MADIHA KORAISHY MD",
    distance: "1.6 mi",
    color: IOS_RED,
    icon: (size: number) => (
      <FontAwesome6 name="user-doctor" size={size || 24} color="white" />
    ),
  },
  {
    title: "METHODIST DALLAS MEDICAL CENTER",
    distance: "2.2 mi",
    color: IOS_BLUE,
    icon: (size: number) => (
      <FontAwesome5 name="hospital" size={size || 24} color="white" />
    ),
  },

  {
    title: "BAYLOR UNIVERSITY MEDICAL CENTER",
    distance: "1.2 mi",
    color: IOS_BLUE,
    icon: (size: number) => (
      <FontAwesome5 name="hospital" size={size || 24} color="white" />
    ),
  },
  {
    title: "YURIY ZEYLIKMAN MD",
    distance: "3.1 mi",
    color: IOS_RED,
    icon: (size: number) => (
      <FontAwesome6 name="user-doctor" size={size || 24} color="white" />
    ),
  },
];

export const WS_URL = "ws://192.168.4.21:58211";
